// Complete list of all 430 calculators
export const allCalculatorDefinitions = [
  // 🏦 Finance Calculators (40)
  { id: 'loan-calculator', slug: 'loan-calculator', name: 'Loan Calculator', category: 'finance' },
  { id: 'mortgage-calculator', slug: 'mortgage-calculator', name: 'Mortgage Calculator', category: 'finance' },
  { id: 'car-loan-calculator', slug: 'car-loan-calculator', name: 'Car Loan Calculator', category: 'finance' },
  { id: 'credit-card-interest', slug: 'credit-card-interest', name: 'Credit Card Interest Calculator', category: 'finance' },
  { id: 'compound-interest', slug: 'compound-interest', name: 'Compound Interest Calculator', category: 'finance' },
  { id: 'savings-goal', slug: 'savings-goal', name: 'Savings Goal Calculator', category: 'finance' },
  { id: 'retirement-calculator', slug: 'retirement-calculator', name: 'Retirement Calculator', category: 'finance' },
  { id: '401k-calculator', slug: '401k-calculator', name: '401k Calculator', category: 'finance' },
  { id: 'roth-ira', slug: 'roth-ira', name: 'Roth IRA Calculator', category: 'finance' },
  { id: 'tax-calculator', slug: 'tax-calculator', name: 'Tax Calculator', category: 'finance' },
  { id: 'vat-calculator', slug: 'vat-calculator', name: 'VAT Calculator', category: 'finance' },
  { id: 'property-tax', slug: 'property-tax', name: 'Property Tax Calculator', category: 'finance' },
  { id: 'inflation-calculator', slug: 'inflation-calculator', name: 'Inflation Calculator', category: 'finance' },
  { id: 'roi-calculator', slug: 'roi-calculator', name: 'ROI Calculator', category: 'finance' },
  { id: 'stock-return', slug: 'stock-return', name: 'Stock Return Calculator', category: 'finance' },
  { id: 'dividend-calculator', slug: 'dividend-calculator', name: 'Dividend Calculator', category: 'finance' },
  { id: 'sip-calculator', slug: 'sip-calculator', name: 'SIP Calculator', category: 'finance' },
  { id: 'mutual-fund', slug: 'mutual-fund', name: 'Mutual Fund Calculator', category: 'finance' },
  { id: 'currency-converter', slug: 'currency-converter', name: 'Currency Converter', category: 'finance' },
  { id: 'crypto-profit', slug: 'crypto-profit', name: 'Crypto Profit Calculator', category: 'finance' },
  { id: 'bitcoin-mining', slug: 'bitcoin-mining', name: 'Bitcoin Mining Calculator', category: 'finance' },
  { id: 'ethereum-gas', slug: 'ethereum-gas', name: 'Ethereum Gas Fee Calculator', category: 'finance' },
  { id: 'nft-profit', slug: 'nft-profit', name: 'NFT Profit Calculator', category: 'finance' },
  { id: 'paycheck-calculator', slug: 'paycheck-calculator', name: 'Paycheck Calculator', category: 'finance' },
  { id: 'salary-calculator', slug: 'salary-calculator', name: 'Salary Calculator', category: 'finance' },
  { id: 'hourly-wage', slug: 'hourly-wage', name: 'Hourly Wage Calculator', category: 'finance' },
  { id: 'overtime-pay', slug: 'overtime-pay', name: 'Overtime Pay Calculator', category: 'finance' },
  { id: 'freelancer-rate', slug: 'freelancer-rate', name: 'Freelancer Rate Calculator', category: 'finance' },
  { id: 'business-loan', slug: 'business-loan', name: 'Business Loan Calculator', category: 'finance' },
  { id: 'refinance-calculator', slug: 'refinance-calculator', name: 'Refinance Calculator', category: 'finance' },
  { id: 'debt-payoff', slug: 'debt-payoff', name: 'Debt Payoff Calculator', category: 'finance' },
  { id: 'amortization', slug: 'amortization', name: 'Amortization Calculator', category: 'finance' },
  { id: 'lease-calculator', slug: 'lease-calculator', name: 'Lease Calculator', category: 'finance' },
  { id: 'break-even', slug: 'break-even', name: 'Break-even Calculator', category: 'finance' },
  { id: 'profit-margin', slug: 'profit-margin', name: 'Profit Margin Calculator', category: 'finance' },
  { id: 'markup-calculator', slug: 'markup-calculator', name: 'Markup Calculator', category: 'finance' },
  { id: 'discount-calculator', slug: 'discount-calculator', name: 'Discount Calculator', category: 'finance' },
  { id: 'sales-tax', slug: 'sales-tax', name: 'Sales Tax Calculator', category: 'finance' },
  { id: 'tip-calculator', slug: 'tip-calculator', name: 'Tip Calculator', category: 'finance' },
  { id: 'currency-arbitrage', slug: 'currency-arbitrage', name: 'Currency Arbitrage Calculator', category: 'finance' },

  // ❤️ Health Calculators (24)
  { id: 'bmi-calculator', slug: 'bmi-calculator', name: 'BMI Calculator', category: 'health' },
  { id: 'bmr-calculator', slug: 'bmr-calculator', name: 'BMR Calculator', category: 'health' },
  { id: 'calorie-calculator', slug: 'calorie-calculator', name: 'Calorie Calculator', category: 'health' },
  { id: 'macro-calculator', slug: 'macro-calculator', name: 'Macro Calculator', category: 'health' },
  { id: 'protein-intake', slug: 'protein-intake', name: 'Protein Intake Calculator', category: 'health' },
  { id: 'water-intake', slug: 'water-intake', name: 'Water Intake Calculator', category: 'health' },
  { id: 'ideal-weight', slug: 'ideal-weight', name: 'Ideal Weight Calculator', category: 'health' },
  { id: 'body-fat', slug: 'body-fat', name: 'Body Fat Calculator', category: 'health' },
  { id: 'tdee-calculator', slug: 'tdee-calculator', name: 'TDEE Calculator', category: 'health' },
  { id: 'running-pace', slug: 'running-pace', name: 'Running Pace Calculator', category: 'health' },
  { id: 'marathon-time', slug: 'marathon-time', name: 'Marathon Time Calculator', category: 'health' },
  { id: 'vo2-max', slug: 'vo2-max', name: 'VO2 Max Calculator', category: 'health' },
  { id: 'heart-rate', slug: 'heart-rate', name: 'Heart Rate Calculator', category: 'health' },
  { id: 'target-heart-rate', slug: 'target-heart-rate', name: 'Target Heart Rate Calculator', category: 'health' },
  { id: 'pregnancy-due-date', slug: 'pregnancy-due-date', name: 'Pregnancy Due Date Calculator', category: 'health' },
  { id: 'ovulation-calculator', slug: 'ovulation-calculator', name: 'Ovulation Calculator', category: 'health' },
  { id: 'conception-calculator', slug: 'conception-calculator', name: 'Conception Calculator', category: 'health' },
  { id: 'pregnancy-weight-gain', slug: 'pregnancy-weight-gain', name: 'Pregnancy Weight Gain Calculator', category: 'health' },
  { id: 'blood-alcohol', slug: 'blood-alcohol', name: 'Blood Alcohol Calculator', category: 'health' },
  { id: 'cholesterol-ratio', slug: 'cholesterol-ratio', name: 'Cholesterol Ratio Calculator', category: 'health' },
  { id: 'insulin-dose', slug: 'insulin-dose', name: 'Insulin Dose Calculator', category: 'health' },
  { id: 'ivf-success', slug: 'ivf-success', name: 'IVF Success Calculator', category: 'health' },
  { id: 'sleep-calculator', slug: 'sleep-calculator', name: 'Sleep Calculator', category: 'health' },
  { id: 'stress-level', slug: 'stress-level', name: 'Stress Level Calculator', category: 'health' },

  // 📚 Education/Science Calculators (41)
  { id: 'gpa-calculator', slug: 'gpa-calculator', name: 'GPA Calculator', category: 'education' },
  { id: 'grade-calculator', slug: 'grade-calculator', name: 'Grade Calculator', category: 'education' },
  { id: 'percentage-calculator', slug: 'percentage-calculator', name: 'Percentage Calculator', category: 'education' },
  { id: 'ratio-calculator', slug: 'ratio-calculator', name: 'Ratio Calculator', category: 'education' },
  { id: 'average-calculator', slug: 'average-calculator', name: 'Average Calculator', category: 'education' },
  { id: 'median-calculator', slug: 'median-calculator', name: 'Median Calculator', category: 'education' },
  { id: 'mode-calculator', slug: 'mode-calculator', name: 'Mode Calculator', category: 'education' },
  { id: 'standard-deviation', slug: 'standard-deviation', name: 'Standard Deviation Calculator', category: 'education' },
  { id: 'probability-calculator', slug: 'probability-calculator', name: 'Probability Calculator', category: 'education' },
  { id: 'permutation-calculator', slug: 'permutation-calculator', name: 'Permutation Calculator', category: 'education' },
  { id: 'combination-calculator', slug: 'combination-calculator', name: 'Combination Calculator', category: 'education' },
  { id: 'z-score-calculator', slug: 'z-score-calculator', name: 'Z-Score Calculator', category: 'education' },
  { id: 't-test-calculator', slug: 't-test-calculator', name: 't-Test Calculator', category: 'education' },
  { id: 'chi-square-calculator', slug: 'chi-square-calculator', name: 'Chi-square Calculator', category: 'education' },
  { id: 'derivative-calculator', slug: 'derivative-calculator', name: 'Derivative Calculator', category: 'education' },
  { id: 'integral-calculator', slug: 'integral-calculator', name: 'Integral Calculator', category: 'education' },
  { id: 'limit-calculator', slug: 'limit-calculator', name: 'Limit Calculator', category: 'education' },
  { id: 'matrix-calculator', slug: 'matrix-calculator', name: 'Matrix Calculator', category: 'education' },
  { id: 'determinant-calculator', slug: 'determinant-calculator', name: 'Determinant Calculator', category: 'education' },
  { id: 'linear-equation-solver', slug: 'linear-equation-solver', name: 'Linear Equation Solver', category: 'education' },
  { id: 'quadratic-equation-solver', slug: 'quadratic-equation-solver', name: 'Quadratic Equation Solver', category: 'education' },
  { id: 'polynomial-calculator', slug: 'polynomial-calculator', name: 'Polynomial Calculator', category: 'education' },
  { id: 'geometry-area-calculator', slug: 'geometry-area-calculator', name: 'Geometry Area Calculator', category: 'education' },
  { id: 'circle-area-calculator', slug: 'circle-area-calculator', name: 'Circle Area Calculator', category: 'education' },
  { id: 'triangle-area-calculator', slug: 'triangle-area-calculator', name: 'Triangle Area Calculator', category: 'education' },
  { id: 'sphere-volume-calculator', slug: 'sphere-volume-calculator', name: 'Sphere Volume Calculator', category: 'education' },
  { id: 'cylinder-volume-calculator', slug: 'cylinder-volume-calculator', name: 'Cylinder Volume Calculator', category: 'education' },
  { id: 'cone-volume-calculator', slug: 'cone-volume-calculator', name: 'Cone Volume Calculator', category: 'education' },
  { id: 'physics-force-calculator', slug: 'physics-force-calculator', name: 'Physics Force Calculator', category: 'education' },
  { id: 'kinetic-energy-calculator', slug: 'kinetic-energy-calculator', name: 'Kinetic Energy Calculator', category: 'education' },
  { id: 'potential-energy-calculator', slug: 'potential-energy-calculator', name: 'Potential Energy Calculator', category: 'education' },
  { id: 'work-calculator', slug: 'work-calculator', name: 'Work Calculator', category: 'education' },
  { id: 'power-calculator', slug: 'power-calculator', name: 'Power Calculator', category: 'education' },
  { id: 'acceleration-calculator', slug: 'acceleration-calculator', name: 'Acceleration Calculator', category: 'education' },
  { id: 'pressure-calculator', slug: 'pressure-calculator', name: 'Pressure Calculator', category: 'education' },
  { id: 'density-calculator', slug: 'density-calculator', name: 'Density Calculator', category: 'education' },
  { id: 'molar-mass-calculator', slug: 'molar-mass-calculator', name: 'Molar Mass Calculator', category: 'education' },
  { id: 'solution-concentration', slug: 'solution-concentration', name: 'Solution Concentration Calculator', category: 'education' },
  { id: 'dilution-calculator', slug: 'dilution-calculator', name: 'Dilution Calculator', category: 'education' },
  { id: 'gas-law-calculator', slug: 'gas-law-calculator', name: 'Gas Law Calculator', category: 'education' },
  { id: 'ph-calculator', slug: 'ph-calculator', name: 'pH Calculator', category: 'education' },

  // ⚙️ Engineering Calculators (20)
  { id: 'ohms-law-calculator', slug: 'ohms-law-calculator', name: 'Ohms Law Calculator', category: 'engineering' },
  { id: 'resistor-color-code', slug: 'resistor-color-code', name: 'Resistor Color Code Calculator', category: 'engineering' },
  { id: 'voltage-divider', slug: 'voltage-divider', name: 'Voltage Divider Calculator', category: 'engineering' },
  { id: 'power-factor', slug: 'power-factor', name: 'Power Factor Calculator', category: 'engineering' },
  { id: 'capacitor-charge', slug: 'capacitor-charge', name: 'Capacitor Charge Calculator', category: 'engineering' },
  { id: 'inductor-energy', slug: 'inductor-energy', name: 'Inductor Energy Calculator', category: 'engineering' },
  { id: 'transformer-calculator', slug: 'transformer-calculator', name: 'Transformer Calculator', category: 'engineering' },
  { id: 'db-calculator', slug: 'db-calculator', name: 'dB Calculator', category: 'engineering' },
  { id: 'antenna-length', slug: 'antenna-length', name: 'Antenna Length Calculator', category: 'engineering' },
  { id: 'beam-deflection', slug: 'beam-deflection', name: 'Beam Deflection Calculator', category: 'engineering' },
  { id: 'torque-calculator', slug: 'torque-calculator', name: 'Torque Calculator', category: 'engineering' },
  { id: 'stress-strain', slug: 'stress-strain', name: 'Stress-Strain Calculator', category: 'engineering' },
  { id: 'concrete-mix', slug: 'concrete-mix', name: 'Concrete Mix Calculator', category: 'engineering' },
  { id: 'paint-calculator', slug: 'paint-calculator', name: 'Paint Calculator', category: 'engineering' },
  { id: 'tile-calculator', slug: 'tile-calculator', name: 'Tile Calculator', category: 'engineering' },
  { id: 'lumber-calculator', slug: 'lumber-calculator', name: 'Lumber Calculator', category: 'engineering' },
  { id: 'roof-pitch', slug: 'roof-pitch', name: 'Roof Pitch Calculator', category: 'engineering' },
  { id: 'hvac-load', slug: 'hvac-load', name: 'HVAC Load Calculator', category: 'engineering' },
  { id: 'solar-panel', slug: 'solar-panel', name: 'Solar Panel Calculator', category: 'engineering' },
  { id: 'battery-life', slug: 'battery-life', name: 'Battery Life Calculator', category: 'engineering' },

  // 🍔 Lifestyle Calculators (20)
  { id: 'age-calculator', slug: 'age-calculator', name: 'Age Calculator', category: 'lifestyle' },
  { id: 'date-difference', slug: 'date-difference', name: 'Date Difference Calculator', category: 'lifestyle' },
  { id: 'countdown-timer', slug: 'countdown-timer', name: 'Countdown Timer Calculator', category: 'lifestyle' },
  { id: 'time-zone-converter', slug: 'time-zone-converter', name: 'Time Zone Converter', category: 'lifestyle' },
  { id: 'calendar-calculator', slug: 'calendar-calculator', name: 'Calendar Calculator', category: 'lifestyle' },
  { id: 'random-number-generator', slug: 'random-number-generator', name: 'Random Number Generator', category: 'lifestyle' },
  { id: 'dice-roller', slug: 'dice-roller', name: 'Dice Roller', category: 'lifestyle' },
  { id: 'coin-flip', slug: 'coin-flip', name: 'Coin Flip Simulator', category: 'lifestyle' },
  { id: 'love-calculator', slug: 'love-calculator', name: 'Love Calculator', category: 'lifestyle' },
  { id: 'name-compatibility', slug: 'name-compatibility', name: 'Name Compatibility Calculator', category: 'lifestyle' },
  { id: 'fuel-cost', slug: 'fuel-cost', name: 'Fuel Cost Calculator', category: 'lifestyle' },
  { id: 'electricity-bill', slug: 'electricity-bill', name: 'Electricity Bill Calculator', category: 'lifestyle' },
  { id: 'cooking-converter', slug: 'cooking-converter', name: 'Cooking Measurement Converter', category: 'lifestyle' },
  { id: 'recipe-nutrition', slug: 'recipe-nutrition', name: 'Recipe Nutrition Calculator', category: 'lifestyle' },
  { id: 'dog-age', slug: 'dog-age', name: 'Dog Age Calculator', category: 'lifestyle' },
  { id: 'cat-age', slug: 'cat-age', name: 'Cat Age Calculator', category: 'lifestyle' },
  { id: 'zodiac-calculator', slug: 'zodiac-calculator', name: 'Zodiac Calculator', category: 'lifestyle' },
  { id: 'chinese-zodiac', slug: 'chinese-zodiac', name: 'Chinese Zodiac Calculator', category: 'lifestyle' },
  { id: 'numerology-calculator', slug: 'numerology-calculator', name: 'Numerology Calculator', category: 'lifestyle' },
  { id: 'biorhythm-calculator', slug: 'biorhythm-calculator', name: 'Biorhythm Calculator', category: 'lifestyle' },

  // 🛡️ Insurance Calculators (8)
  { id: 'life-insurance', slug: 'life-insurance', name: 'Life Insurance Calculator', category: 'insurance' },
  { id: 'health-insurance', slug: 'health-insurance', name: 'Health Insurance Premium Calculator', category: 'insurance' },
  { id: 'car-insurance', slug: 'car-insurance', name: 'Car Insurance Calculator', category: 'insurance' },
  { id: 'home-insurance', slug: 'home-insurance', name: 'Home Insurance Calculator', category: 'insurance' },
  { id: 'travel-insurance', slug: 'travel-insurance', name: 'Travel Insurance Calculator', category: 'insurance' },
  { id: 'pet-insurance', slug: 'pet-insurance', name: 'Pet Insurance Calculator', category: 'insurance' },
  { id: 'critical-illness', slug: 'critical-illness', name: 'Critical Illness Insurance Calculator', category: 'insurance' },
  { id: 'retirement-annuity', slug: 'retirement-annuity', name: 'Retirement Annuity Calculator', category: 'insurance' },

  // 🌍 Environment Calculators (10)
  { id: 'carbon-footprint', slug: 'carbon-footprint', name: 'Carbon Footprint Calculator', category: 'environment' },
  { id: 'solar-savings', slug: 'solar-savings', name: 'Solar Savings Calculator', category: 'environment' },
  { id: 'ev-charging-cost', slug: 'ev-charging-cost', name: 'EV Charging Cost Calculator', category: 'environment' },
  { id: 'carbon-offset', slug: 'carbon-offset', name: 'Carbon Offset Calculator', category: 'environment' },
  { id: 'solar-roi', slug: 'solar-roi', name: 'Solar ROI Calculator', category: 'environment' },
  { id: 'wind-energy', slug: 'wind-energy', name: 'Wind Energy Calculator', category: 'environment' },
  { id: 'hydro-power', slug: 'hydro-power', name: 'Hydro Power Calculator', category: 'environment' },
  { id: 'ev-range', slug: 'ev-range', name: 'EV Range Calculator', category: 'environment' },
  { id: 'ev-charging-time', slug: 'ev-charging-time', name: 'EV Charging Time Calculator', category: 'environment' },
  { id: 'ev-cost-per-km', slug: 'ev-cost-per-km', name: 'EV Cost per Km Calculator', category: 'environment' },

  // 🔁 Unit Conversion Calculators (20)
  { id: 'length-converter', slug: 'length-converter', name: 'Length Converter', category: 'conversion' },
  { id: 'weight-converter', slug: 'weight-converter', name: 'Weight Converter', category: 'conversion' },
  { id: 'temperature-converter', slug: 'temperature-converter', name: 'Temperature Converter', category: 'conversion' },
  { id: 'speed-converter', slug: 'speed-converter', name: 'Speed Converter', category: 'conversion' },
  { id: 'area-converter', slug: 'area-converter', name: 'Area Converter', category: 'conversion' },
  { id: 'volume-converter', slug: 'volume-converter', name: 'Volume Converter', category: 'conversion' },
  { id: 'energy-converter', slug: 'energy-converter', name: 'Energy Converter', category: 'conversion' },
  { id: 'power-converter', slug: 'power-converter', name: 'Power Converter', category: 'conversion' },
  { id: 'pressure-converter', slug: 'pressure-converter', name: 'Pressure Converter', category: 'conversion' },
  { id: 'time-converter', slug: 'time-converter', name: 'Time Converter', category: 'conversion' },
  { id: 'frequency-converter', slug: 'frequency-converter', name: 'Frequency Converter', category: 'conversion' },
  { id: 'angle-converter', slug: 'angle-converter', name: 'Angle Converter', category: 'conversion' },
  { id: 'currency-historical', slug: 'currency-historical', name: 'Currency Historical Converter', category: 'conversion' },
  { id: 'cooking-converter', slug: 'cooking-converter', name: 'Cooking Converter', category: 'conversion' },
  { id: 'shoe-size-converter', slug: 'shoe-size-converter', name: 'Shoe Size Converter', category: 'conversion' },
  { id: 'clothing-size-converter', slug: 'clothing-size-converter', name: 'Clothing Size Converter', category: 'conversion' },
  { id: 'blood-sugar-converter', slug: 'blood-sugar-converter', name: 'Blood Sugar Converter', category: 'conversion' },
  { id: 'fuel-efficiency-converter', slug: 'fuel-efficiency-converter', name: 'Fuel Efficiency Converter', category: 'conversion' },
  { id: 'data-storage-converter', slug: 'data-storage-converter', name: 'Data Storage Converter', category: 'conversion' },
  { id: 'bandwidth-converter', slug: 'bandwidth-converter', name: 'Bandwidth Converter', category: 'conversion' },

  // 📈 Business Calculators (15)
  { id: 'break-even-point', slug: 'break-even-point', name: 'Break-even Point Calculator', category: 'business' },
  { id: 'roi-marketing', slug: 'roi-marketing', name: 'ROI Marketing Calculator', category: 'business' },
  { id: 'customer-acquisition-cost', slug: 'customer-acquisition-cost', name: 'Customer Acquisition Cost Calculator', category: 'business' },
  { id: 'ltv-calculator', slug: 'ltv-calculator', name: 'LTV Calculator', category: 'business' },
  { id: 'churn-rate', slug: 'churn-rate', name: 'Churn Rate Calculator', category: 'business' },
  { id: 'conversion-rate', slug: 'conversion-rate', name: 'Conversion Rate Calculator', category: 'business' },
  { id: 'cpc-campaign', slug: 'cpc-campaign', name: 'CPC Campaign Calculator', category: 'business' },
  { id: 'cpm-calculator', slug: 'cpm-calculator', name: 'CPM Calculator', category: 'business' },
  { id: 'affiliate-earnings', slug: 'affiliate-earnings', name: 'Affiliate Earnings Calculator', category: 'business' },
  { id: 'saas-pricing', slug: 'saas-pricing', name: 'SaaS Pricing Calculator', category: 'business' },
  { id: 'subscription-revenue', slug: 'subscription-revenue', name: 'Subscription Revenue Calculator', category: 'business' },
  { id: 'freelancer-profit', slug: 'freelancer-profit', name: 'Freelancer Profit Calculator', category: 'business' },
  { id: 'consulting-rate', slug: 'consulting-rate', name: 'Consulting Hourly Rate Calculator', category: 'business' },
  { id: 'invoice-payment', slug: 'invoice-payment', name: 'Invoice Payment Calculator', category: 'business' },
  { id: 'employee-payroll', slug: 'employee-payroll', name: 'Employee Payroll Calculator', category: 'business' },

  // 💻 Technology Calculators (15)
  { id: 'website-bandwidth', slug: 'website-bandwidth', name: 'Website Bandwidth Calculator', category: 'technology' },
  { id: 'web-hosting-cost', slug: 'web-hosting-cost', name: 'Web Hosting Cost Calculator', category: 'technology' },
  { id: 'cloud-storage', slug: 'cloud-storage', name: 'Cloud Storage Calculator', category: 'technology' },
  { id: 'api-usage', slug: 'api-usage', name: 'API Usage Calculator', category: 'technology' },
  { id: 'data-transfer', slug: 'data-transfer', name: 'Data Transfer Calculator', category: 'technology' },
  { id: 'download-time', slug: 'download-time', name: 'Download Time Calculator', category: 'technology' },
  { id: 'password-strength', slug: 'password-strength', name: 'Password Strength Calculator', category: 'technology' },
  { id: 'hash-rate', slug: 'hash-rate', name: 'Hash Rate Calculator', category: 'technology' },
  { id: 'ip-subnet', slug: 'ip-subnet', name: 'IP Subnet Calculator', category: 'technology' },
  { id: 'ping-latency', slug: 'ping-latency', name: 'Ping Latency Calculator', category: 'technology' },
  { id: 'database-storage', slug: 'database-storage', name: 'Database Storage Calculator', category: 'technology' },
  { id: 'email-sending-cost', slug: 'email-sending-cost', name: 'Email Sending Cost Calculator', category: 'technology' },
  { id: 'mobile-data-usage', slug: 'mobile-data-usage', name: 'Mobile Data Usage Calculator', category: 'technology' },
  { id: 'streaming-bandwidth', slug: 'streaming-bandwidth', name: 'Streaming Bandwidth Calculator', category: 'technology' },
  { id: 'website-uptime', slug: 'website-uptime', name: 'Website Uptime Calculator', category: 'technology' },

  // 📐 Mathematics Calculators (20)
  { id: 'logarithm-calculator', slug: 'logarithm-calculator', name: 'Logarithm Calculator', category: 'mathematics' },
  { id: 'exponent-calculator', slug: 'exponent-calculator', name: 'Exponent Calculator', category: 'mathematics' },
  { id: 'factorial-calculator', slug: 'factorial-calculator', name: 'Factorial Calculator', category: 'mathematics' },
  { id: 'prime-number-checker', slug: 'prime-number-checker', name: 'Prime Number Checker', category: 'mathematics' },
  { id: 'gcf-calculator', slug: 'gcf-calculator', name: 'GCF Calculator', category: 'mathematics' },
  { id: 'lcm-calculator', slug: 'lcm-calculator', name: 'LCM Calculator', category: 'mathematics' },
  { id: 'percent-error', slug: 'percent-error', name: 'Percent Error Calculator', category: 'mathematics' },
  { id: 'proportion-calculator', slug: 'proportion-calculator', name: 'Proportion Calculator', category: 'mathematics' },
  { id: 'mean-median-mode', slug: 'mean-median-mode', name: 'Mean Median Mode Calculator', category: 'mathematics' },
  { id: 'quartile-calculator', slug: 'quartile-calculator', name: 'Quartile Calculator', category: 'mathematics' },
  { id: 'variance-calculator', slug: 'variance-calculator', name: 'Variance Calculator', category: 'mathematics' },
  { id: 'correlation-coefficient', slug: 'correlation-coefficient', name: 'Correlation Coefficient Calculator', category: 'mathematics' },
  { id: 'regression-calculator', slug: 'regression-calculator', name: 'Regression Calculator', category: 'mathematics' },
  { id: 'bayes-theorem', slug: 'bayes-theorem', name: 'Bayes Theorem Calculator', category: 'mathematics' },
  { id: 'probability-distribution', slug: 'probability-distribution', name: 'Probability Distribution Calculator', category: 'mathematics' },
  { id: 'binomial-probability', slug: 'binomial-probability', name: 'Binomial Probability Calculator', category: 'mathematics' },
  { id: 'normal-distribution', slug: 'normal-distribution', name: 'Normal Distribution Calculator', category: 'mathematics' },
  { id: 'poisson-distribution', slug: 'poisson-distribution', name: 'Poisson Distribution Calculator', category: 'mathematics' },
  { id: 'anova-calculator', slug: 'anova-calculator', name: 'ANOVA Calculator', category: 'mathematics' },
  { id: 'confidence-interval', slug: 'confidence-interval', name: 'Confidence Interval Calculator', category: 'mathematics' },

  // 📦 Logistics Calculators (10)
  { id: 'fuel-cost-split', slug: 'fuel-cost-split', name: 'Fuel Cost Split Calculator', category: 'logistics' },
  { id: 'road-trip-cost', slug: 'road-trip-cost', name: 'Road Trip Cost Calculator', category: 'logistics' },
  { id: 'toll-cost', slug: 'toll-cost', name: 'Toll Cost Calculator', category: 'logistics' },
  { id: 'shipping-cost', slug: 'shipping-cost', name: 'Shipping Cost Calculator', category: 'logistics' },
  { id: 'package-volume-weight', slug: 'package-volume-weight', name: 'Package Volume Weight Calculator', category: 'logistics' },
  { id: 'delivery-time', slug: 'delivery-time', name: 'Delivery Time Calculator', category: 'logistics' },
  { id: 'co2-emission-travel', slug: 'co2-emission-travel', name: 'CO2 Emission from Travel Calculator', category: 'logistics' },
  { id: 'freight-class', slug: 'freight-class', name: 'Freight Class Calculator', category: 'logistics' },
  { id: 'container-loading', slug: 'container-loading', name: 'Container Loading Calculator', category: 'logistics' },
  { id: 'route-optimization', slug: 'route-optimization', name: 'Route Optimization Calculator', category: 'logistics' },

  // 🏠 Household Calculators (15)
  { id: 'home-budget', slug: 'home-budget', name: 'Home Budget Calculator', category: 'household' },
  { id: 'grocery-cost', slug: 'grocery-cost', name: 'Grocery Cost Calculator', category: 'household' },
  { id: 'electricity-usage', slug: 'electricity-usage', name: 'Electricity Usage Calculator', category: 'household' },
  { id: 'water-bill', slug: 'water-bill', name: 'Water Bill Calculator', category: 'household' },
  { id: 'internet-bill', slug: 'internet-bill', name: 'Internet Bill Calculator', category: 'household' },
  { id: 'phone-bill', slug: 'phone-bill', name: 'Phone Bill Calculator', category: 'household' },
  { id: 'furniture-cost', slug: 'furniture-cost', name: 'Furniture Cost Calculator', category: 'household' },
  { id: 'home-renovation', slug: 'home-renovation', name: 'Home Renovation Calculator', category: 'household' },
  { id: 'paint-coverage', slug: 'paint-coverage', name: 'Paint Coverage Calculator', category: 'household' },
  { id: 'wallpaper-roll', slug: 'wallpaper-roll', name: 'Wallpaper Roll Calculator', category: 'household' },
  { id: 'garden-soil', slug: 'garden-soil', name: 'Garden Soil Calculator', category: 'household' },
  { id: 'lawn-fertilizer', slug: 'lawn-fertilizer', name: 'Lawn Fertilizer Calculator', category: 'household' },
  { id: 'moving-cost', slug: 'moving-cost', name: 'Moving Cost Calculator', category: 'household' },
  { id: 'cleaning-supplies', slug: 'cleaning-supplies', name: 'Cleaning Supplies Calculator', category: 'household' },
  { id: 'appliance-energy', slug: 'appliance-energy', name: 'Appliance Energy Calculator', category: 'household' },

  // 🧪 Miscellaneous Calculators (172 remaining)
  // Additional Finance Calculators
  { id: 'federal-income-tax', slug: 'federal-income-tax', name: 'Federal Income Tax Calculator', category: 'miscellaneous' },
  { id: 'state-tax-ca', slug: 'state-tax-ca', name: 'California State Tax Calculator', category: 'miscellaneous' },
  { id: 'state-tax-ny', slug: 'state-tax-ny', name: 'New York State Tax Calculator', category: 'miscellaneous' },
  { id: 'state-tax-tx', slug: 'state-tax-tx', name: 'Texas State Tax Calculator', category: 'miscellaneous' },
  { id: 'germany-income-tax', slug: 'germany-income-tax', name: 'Germany Income Tax Calculator', category: 'miscellaneous' },
  { id: 'france-property-tax', slug: 'france-property-tax', name: 'France Property Tax Calculator', category: 'miscellaneous' },
  { id: 'japan-social-insurance', slug: 'japan-social-insurance', name: 'Japan Social Insurance Calculator', category: 'miscellaneous' },
  { id: 'india-gst', slug: 'india-gst', name: 'India GST Calculator', category: 'miscellaneous' },
  { id: 'thailand-income-tax', slug: 'thailand-income-tax', name: 'Thailand Income Tax Calculator', category: 'miscellaneous' },
  { id: 'uk-stamp-duty', slug: 'uk-stamp-duty', name: 'UK Stamp Duty Calculator', category: 'miscellaneous' },
  { id: 'australia-superannuation', slug: 'australia-superannuation', name: 'Australia Superannuation Calculator', category: 'miscellaneous' },
  { id: 'canada-rrsp', slug: 'canada-rrsp', name: 'Canada RRSP Calculator', category: 'miscellaneous' },
  { id: 'cagr-calculator', slug: 'cagr-calculator', name: 'CAGR Calculator', category: 'miscellaneous' },
  { id: 'npv-calculator', slug: 'npv-calculator', name: 'NPV Calculator', category: 'miscellaneous' },
  { id: 'irr-calculator', slug: 'irr-calculator', name: 'IRR Calculator', category: 'miscellaneous' },
  { id: 'bond-yield', slug: 'bond-yield', name: 'Bond Yield Calculator', category: 'miscellaneous' },
  { id: 'dti-ratio', slug: 'dti-ratio', name: 'Debt-to-Income Ratio Calculator', category: 'miscellaneous' },
  { id: 'ltv-ratio', slug: 'ltv-ratio', name: 'Loan-to-Value Ratio Calculator', category: 'miscellaneous' },
  { id: 'ebitda-margin', slug: 'ebitda-margin', name: 'EBITDA Margin Calculator', category: 'miscellaneous' },
  { id: 'enterprise-value', slug: 'enterprise-value', name: 'Enterprise Value Calculator', category: 'miscellaneous' },
  { id: 'pension-calculator', slug: 'pension-calculator', name: 'Pension Calculator', category: 'miscellaneous' },
  { id: 'social-security-benefit', slug: 'social-security-benefit', name: 'Social Security Benefit Calculator', category: 'miscellaneous' },
  { id: 'annuity-vs-lump-sum', slug: 'annuity-vs-lump-sum', name: 'Annuity vs Lump Sum Calculator', category: 'miscellaneous' },
  { id: 'rent-vs-buy', slug: 'rent-vs-buy', name: 'Rent vs Buy Calculator', category: 'miscellaneous' },
  { id: 'tuition-loan', slug: 'tuition-loan', name: 'Tuition Loan Calculator', category: 'miscellaneous' },
  { id: 'payday-loan', slug: 'payday-loan', name: 'Payday Loan Calculator', category: 'miscellaneous' },
  { id: 'hedge-fund-roi', slug: 'hedge-fund-roi', name: 'Hedge Fund ROI Calculator', category: 'miscellaneous' },
  { id: 'private-equity-roi', slug: 'private-equity-roi', name: 'Private Equity ROI Calculator', category: 'miscellaneous' },
  { id: 'venture-capital-roi', slug: 'venture-capital-roi', name: 'Venture Capital ROI Calculator', category: 'miscellaneous' },
  { id: 'option-pricing', slug: 'option-pricing', name: 'Option Pricing Calculator', category: 'miscellaneous' },
  
  // Additional Health Calculators
  { id: 'body-surface-area', slug: 'body-surface-area', name: 'Body Surface Area Calculator', category: 'miscellaneous' },
  { id: 'waist-to-hip-ratio', slug: 'waist-to-hip-ratio', name: 'Waist-to-Hip Ratio Calculator', category: 'miscellaneous' },
  { id: 'ideal-body-fat', slug: 'ideal-body-fat', name: 'Ideal Body Fat Calculator', category: 'miscellaneous' },
  { id: 'calorie-burn-exercise', slug: 'calorie-burn-exercise', name: 'Calorie Burn by Exercise Calculator', category: 'miscellaneous' },
  { id: 'step-to-calorie', slug: 'step-to-calorie', name: 'Step to Calorie Converter', category: 'miscellaneous' },
  { id: 'blood-pressure-risk', slug: 'blood-pressure-risk', name: 'Blood Pressure Risk Calculator', category: 'miscellaneous' },
  { id: 'diabetes-risk', slug: 'diabetes-risk', name: 'Diabetes Risk Score Calculator', category: 'miscellaneous' },
  { id: 'ayurvedic-bmi', slug: 'ayurvedic-bmi', name: 'Ayurvedic BMI Calculator', category: 'miscellaneous' },
  { id: 'japanese-food-calorie', slug: 'japanese-food-calorie', name: 'Japanese Food Calorie Calculator', category: 'miscellaneous' },
  { id: 'thai-food-calorie', slug: 'thai-food-calorie', name: 'Thai Food Calorie Calculator', category: 'miscellaneous' },
  { id: 'ivf-cost-estimator', slug: 'ivf-cost-estimator', name: 'IVF Cost Estimator', category: 'miscellaneous' },
  { id: 'cholesterol-ldl-hdl', slug: 'cholesterol-ldl-hdl', name: 'Cholesterol LDL/HDL Ratio', category: 'miscellaneous' },
  { id: 'life-expectancy', slug: 'life-expectancy', name: 'Life Expectancy Calculator', category: 'miscellaneous' },
  { id: 'lung-capacity', slug: 'lung-capacity', name: 'Lung Capacity Calculator', category: 'miscellaneous' },
  { id: 'water-loss-sweat', slug: 'water-loss-sweat', name: 'Water Loss (Sweat) Calculator', category: 'miscellaneous' },

  // Fun/Novelty Calculators
  { id: 'meme-worth', slug: 'meme-worth', name: 'Meme Worth Calculator', category: 'miscellaneous' },
  { id: 'gaming-time', slug: 'gaming-time', name: 'Gaming Time Calculator', category: 'miscellaneous' },
  { id: 'level-xp', slug: 'level-xp', name: 'Level XP Calculator', category: 'miscellaneous' },
  { id: 'gacha-probability', slug: 'gacha-probability', name: 'Gacha Probability Calculator', category: 'miscellaneous' },
  { id: 'pet-age-converter', slug: 'pet-age-converter', name: 'Pet Age Converter', category: 'miscellaneous' },
  { id: 'relationship-calculator', slug: 'relationship-calculator', name: 'Relationship Calculator', category: 'miscellaneous' },
  { id: 'baby-name-compatibility', slug: 'baby-name-compatibility', name: 'Baby Name Compatibility Calculator', category: 'miscellaneous' },
  { id: 'birthday-calculator', slug: 'birthday-calculator', name: 'Birthday Calculator', category: 'miscellaneous' },
  { id: 'lucky-number', slug: 'lucky-number', name: 'Lucky Number Calculator', category: 'miscellaneous' },
  { id: 'astrology-calculator', slug: 'astrology-calculator', name: 'Astrology Calculator', category: 'miscellaneous' },
  { id: 'chinese-zodiac-compatibility', slug: 'chinese-zodiac-compatibility', name: 'Chinese Zodiac Compatibility Calculator', category: 'miscellaneous' },
  { id: 'tarot-card', slug: 'tarot-card', name: 'Tarot Card Calculator', category: 'miscellaneous' },
  { id: 'horoscope-love', slug: 'horoscope-love', name: 'Horoscope Love Calculator', category: 'miscellaneous' },
  { id: 'wedding-date', slug: 'wedding-date', name: 'Wedding Date Calculator', category: 'miscellaneous' },

  // Additional Miscellaneous
  { id: 'age-gap', slug: 'age-gap', name: 'Age Gap Calculator', category: 'miscellaneous' },
  { id: 'pregnancy-conception', slug: 'pregnancy-conception', name: 'Pregnancy Conception Calculator', category: 'miscellaneous' },
  { id: 'moon-phase', slug: 'moon-phase', name: 'Moon Phase Calculator', category: 'miscellaneous' },
  { id: 'sunrise-sunset', slug: 'sunrise-sunset', name: 'Sunrise Sunset Calculator', category: 'miscellaneous' },
  { id: 'prayer-time', slug: 'prayer-time', name: 'Prayer Time Calculator', category: 'miscellaneous' },
  { id: 'lottery-odds', slug: 'lottery-odds', name: 'Lottery Odds Calculator', category: 'miscellaneous' },
  { id: 'hex-to-binary', slug: 'hex-to-binary', name: 'Hex to Binary Calculator', category: 'miscellaneous' },
  { id: 'binary-to-decimal', slug: 'binary-to-decimal', name: 'Binary to Decimal Calculator', category: 'miscellaneous' },
  { id: 'roman-numeral', slug: 'roman-numeral', name: 'Roman Numeral Converter', category: 'miscellaneous' },
  { id: 'morse-code', slug: 'morse-code', name: 'Morse Code Translator', category: 'miscellaneous' },
  { id: 'text-to-binary', slug: 'text-to-binary', name: 'Text to Binary Calculator', category: 'miscellaneous' },
  { id: 'ascii-code', slug: 'ascii-code', name: 'ASCII Code Calculator', category: 'miscellaneous' },
  { id: 'qr-code-value', slug: 'qr-code-value', name: 'QR Code Value Calculator', category: 'miscellaneous' },
  { id: 'ip-address-locator', slug: 'ip-address-locator', name: 'IP Address Locator Calculator', category: 'miscellaneous' },
  { id: 'age-in-months', slug: 'age-in-months', name: 'Age in Months Calculator', category: 'miscellaneous' },
  { id: 'anniversary-calculator', slug: 'anniversary-calculator', name: 'Anniversary Calculator', category: 'miscellaneous' },
  { id: 'day-of-week', slug: 'day-of-week', name: 'Day of Week Calculator', category: 'miscellaneous' },
  { id: 'work-days', slug: 'work-days', name: 'Work Days Calculator', category: 'miscellaneous' },
  { id: 'age-in-weeks', slug: 'age-in-weeks', name: 'Age in Weeks Calculator', category: 'miscellaneous' },
  { id: 'age-in-days', slug: 'age-in-days', name: 'Age in Days Calculator', category: 'miscellaneous' },
  { id: 'work-hours-left', slug: 'work-hours-left', name: 'Work Hours Left in Year Calculator', category: 'miscellaneous' },
  { id: 'days-until-payday', slug: 'days-until-payday', name: 'Days Until Payday Calculator', category: 'miscellaneous' },
  { id: 'ramadan-fasting', slug: 'ramadan-fasting', name: 'Ramadan Fasting Time Calculator', category: 'miscellaneous' },
  { id: 'christian-lent', slug: 'christian-lent', name: 'Christian Lent Countdown Calculator', category: 'miscellaneous' },
  { id: 'buddhist-lent', slug: 'buddhist-lent', name: 'Buddhist Lent Day Calculator', category: 'miscellaneous' },
  { id: 'lunar-eclipse', slug: 'lunar-eclipse', name: 'Next Lunar Eclipse Calculator', category: 'miscellaneous' },
  { id: 'solar-eclipse', slug: 'solar-eclipse', name: 'Next Solar Eclipse Calculator', category: 'miscellaneous' },
  { id: 'moon-age', slug: 'moon-age', name: 'Moon Age Calculator', category: 'miscellaneous' },
  { id: 'star-sign-finder', slug: 'star-sign-finder', name: 'Star Sign Finder', category: 'miscellaneous' },
  { id: 'angel-number', slug: 'angel-number', name: 'Angel Number Calculator', category: 'miscellaneous' },
  { id: 'tarot-spread', slug: 'tarot-spread', name: 'Tarot Spread Generator', category: 'miscellaneous' },

  // Emerging/Special Calculators
  { id: 'streaming-subscription', slug: 'streaming-subscription', name: 'Streaming Subscription Calculator', category: 'miscellaneous' },
  { id: 'gaming-pc-power', slug: 'gaming-pc-power', name: 'Gaming PC Power Calculator', category: 'miscellaneous' },
  { id: 'youtube-income', slug: 'youtube-income', name: 'YouTube Income Calculator', category: 'miscellaneous' },
  { id: 'tiktok-earnings', slug: 'tiktok-earnings', name: 'TikTok Earnings Calculator', category: 'miscellaneous' },
  { id: 'affiliate-roi', slug: 'affiliate-roi', name: 'Affiliate ROI Calculator', category: 'miscellaneous' },
  { id: 'website-traffic-value', slug: 'website-traffic-value', name: 'Website Traffic Value Calculator', category: 'miscellaneous' },
  { id: 'domain-worth', slug: 'domain-worth', name: 'Domain Worth Calculator', category: 'miscellaneous' },

  // Additional Education Calculators
  { id: 'percentage-increase', slug: 'percentage-increase', name: 'Percentage Increase Calculator', category: 'miscellaneous' },
  { id: 'percentage-decrease', slug: 'percentage-decrease', name: 'Percentage Decrease Calculator', category: 'miscellaneous' },
  { id: 'ratio-simplifier', slug: 'ratio-simplifier', name: 'Ratio Simplifier', category: 'miscellaneous' },
  { id: 'fraction-to-decimal', slug: 'fraction-to-decimal', name: 'Fraction to Decimal Converter', category: 'miscellaneous' },
  { id: 'decimal-to-fraction', slug: 'decimal-to-fraction', name: 'Decimal to Fraction Converter', category: 'miscellaneous' },
  { id: 'prime-factorization', slug: 'prime-factorization', name: 'Prime Factorization Calculator', category: 'miscellaneous' },
  { id: 'square-root', slug: 'square-root', name: 'Square Root Calculator', category: 'miscellaneous' },
  { id: 'cube-root', slug: 'cube-root', name: 'Cube Root Calculator', category: 'miscellaneous' },
  { id: 'log-base-n', slug: 'log-base-n', name: 'Log Base N Calculator', category: 'miscellaneous' },
  { id: 'exponential-growth', slug: 'exponential-growth', name: 'Exponential Growth Calculator', category: 'miscellaneous' },
  { id: 'time-until-exam', slug: 'time-until-exam', name: 'Time Until Exam Calculator', category: 'miscellaneous' },
  { id: 'grade-needed', slug: 'grade-needed', name: 'Grade Needed Calculator', category: 'miscellaneous' },
  { id: 'sat-score-converter', slug: 'sat-score-converter', name: 'SAT Score Converter', category: 'miscellaneous' },
  { id: 'act-score-converter', slug: 'act-score-converter', name: 'ACT Score Converter', category: 'miscellaneous' },
  { id: 'gre-to-gmat', slug: 'gre-to-gmat', name: 'GRE to GMAT Converter', category: 'miscellaneous' },
  { id: 'abitur-grade', slug: 'abitur-grade', name: 'Abitur Grade Calculator', category: 'miscellaneous' },
  { id: 'jee-rank-predictor', slug: 'jee-rank-predictor', name: 'JEE Rank Predictor', category: 'miscellaneous' },
  { id: 'gate-score', slug: 'gate-score', name: 'GATE Score Calculator', category: 'miscellaneous' },
  { id: 'bac-grade', slug: 'bac-grade', name: 'BAC Grade Calculator', category: 'miscellaneous' },
  { id: 'hsc-mark', slug: 'hsc-mark', name: 'HSC Mark Calculator', category: 'miscellaneous' },
  { id: 'weighted-average', slug: 'weighted-average', name: 'Weighted Average Calculator', category: 'miscellaneous' },
  { id: 'harmonic-mean', slug: 'harmonic-mean', name: 'Harmonic Mean Calculator', category: 'miscellaneous' },
  { id: 'root-mean-square', slug: 'root-mean-square', name: 'Root Mean Square Calculator', category: 'miscellaneous' },
  { id: 'probability-of-event', slug: 'probability-of-event', name: 'Probability of Event Calculator', category: 'miscellaneous' },

  // Additional Engineering/Tech Calculators
  { id: 'current-density', slug: 'current-density', name: 'Current Density Calculator', category: 'miscellaneous' },
  { id: 'power-loss-cable', slug: 'power-loss-cable', name: 'Power Loss in Cable Calculator', category: 'miscellaneous' },
  { id: 'battery-charge-time', slug: 'battery-charge-time', name: 'Battery Charge Time Calculator', category: 'miscellaneous' },
  { id: 'solar-inverter-size', slug: 'solar-inverter-size', name: 'Solar Inverter Size Calculator', category: 'miscellaneous' },
  { id: 'wind-turbine-power', slug: 'wind-turbine-power', name: 'Wind Turbine Power Calculator', category: 'miscellaneous' },
  { id: 'steel-weight', slug: 'steel-weight', name: 'Steel Weight Calculator', category: 'miscellaneous' },
  { id: 'brick-calculator', slug: 'brick-calculator', name: 'Brick Calculator', category: 'miscellaneous' },
  { id: 'asphalt-volume', slug: 'asphalt-volume', name: 'Asphalt Volume Calculator', category: 'miscellaneous' },
  { id: 'concrete-slab-volume', slug: 'concrete-slab-volume', name: 'Concrete Slab Volume Calculator', category: 'miscellaneous' },
  { id: 'pipe-flow', slug: 'pipe-flow', name: 'Pipe Flow Calculator', category: 'miscellaneous' },
  { id: 'heat-transfer', slug: 'heat-transfer', name: 'Heat Transfer Calculator', category: 'miscellaneous' },
  { id: 'signal-to-noise', slug: 'signal-to-noise', name: 'Signal-to-Noise Ratio Calculator', category: 'miscellaneous' },
  { id: 'domain-age-checker', slug: 'domain-age-checker', name: 'Domain Age Checker', category: 'miscellaneous' },
  { id: 'ssl-expiry-checker', slug: 'ssl-expiry-checker', name: 'SSL Expiry Checker', category: 'miscellaneous' },

  // Additional Lifestyle Calculators
  { id: 'life-expectancy-predictor', slug: 'life-expectancy-predictor', name: 'Life Expectancy Age Predictor', category: 'miscellaneous' },
  { id: 'lucky-color', slug: 'lucky-color', name: 'Lucky Color Calculator', category: 'miscellaneous' },
  { id: 'baby-gender-predictor', slug: 'baby-gender-predictor', name: 'Baby Gender Predictor', category: 'miscellaneous' },
  { id: 'name-numerology', slug: 'name-numerology', name: 'Name Numerology Calculator', category: 'miscellaneous' },
  { id: 'blood-type-compatibility', slug: 'blood-type-compatibility', name: 'Blood Type Compatibility', category: 'miscellaneous' },
  { id: 'wedding-anniversary-symbol', slug: 'wedding-anniversary-symbol', name: 'Wedding Anniversary Symbol Calculator', category: 'miscellaneous' },
  { id: 'retirement-age', slug: 'retirement-age', name: 'Retirement Age Calculator', category: 'miscellaneous' },
  { id: 'days-until-new-year', slug: 'days-until-new-year', name: 'Days Until New Year Calculator', category: 'miscellaneous' },
  { id: 'days-until-birthday', slug: 'days-until-birthday', name: 'Days Until Birthday Calculator', category: 'miscellaneous' },
  { id: 'days-until-vacation', slug: 'days-until-vacation', name: 'Days Until Vacation Calculator', category: 'miscellaneous' },
  { id: 'zodiac-chinese-year', slug: 'zodiac-chinese-year', name: 'Zodiac Chinese Year Finder', category: 'miscellaneous' },
  { id: 'horoscope-yearly-luck', slug: 'horoscope-yearly-luck', name: 'Horoscope Yearly Luck Calculator', category: 'miscellaneous' },
  { id: 'lucky-draw-number', slug: 'lucky-draw-number', name: 'Lucky Draw Number Generator', category: 'miscellaneous' },
  { id: 'random-password', slug: 'random-password', name: 'Random Password Generator', category: 'miscellaneous' },
  { id: 'meme-generator-roi', slug: 'meme-generator-roi', name: 'Meme Generator ROI Calculator', category: 'miscellaneous' },
  { id: 'travel-budget-split', slug: 'travel-budget-split', name: 'Travel Budget Split Calculator', category: 'miscellaneous' },
  { id: 'coffee-cost-per-year', slug: 'coffee-cost-per-year', name: 'Coffee Cost Per Year Calculator', category: 'miscellaneous' },
  { id: 'daily-screen-time', slug: 'daily-screen-time', name: 'Daily Screen Time Calculator', category: 'miscellaneous' },
  { id: 'social-media-usage', slug: 'social-media-usage', name: 'Social Media Usage Time Calculator', category: 'miscellaneous' },
  { id: 'happiness-index', slug: 'happiness-index', name: 'Happiness Index Calculator', category: 'miscellaneous' },

  // Additional Environment Calculators
  { id: 'ev-tax-credit', slug: 'ev-tax-credit', name: 'EV Tax Credit Calculator', category: 'miscellaneous' },
  { id: 'solar-feed-in-tariff', slug: 'solar-feed-in-tariff', name: 'Solar Feed-in Tariff Calculator', category: 'miscellaneous' },
  { id: 'carbon-tax', slug: 'carbon-tax', name: 'Carbon Tax Calculator', category: 'miscellaneous' },
  { id: 'renewable-energy-roi', slug: 'renewable-energy-roi', name: 'Renewable Energy ROI Calculator', category: 'miscellaneous' },
  { id: 'battery-storage-size', slug: 'battery-storage-size', name: 'Battery Storage Size Calculator', category: 'miscellaneous' },
  { id: 'wind-turbine-roi', slug: 'wind-turbine-roi', name: 'Wind Turbine ROI Calculator', category: 'miscellaneous' },
  { id: 'ev-co2-saving', slug: 'ev-co2-saving', name: 'EV CO2 Saving Calculator', category: 'miscellaneous' },
  { id: 'recycling-impact', slug: 'recycling-impact', name: 'Recycling Impact Calculator', category: 'miscellaneous' },
  { id: 'plastic-footprint', slug: 'plastic-footprint', name: 'Plastic Footprint Calculator', category: 'miscellaneous' },
  { id: 'water-usage-footprint', slug: 'water-usage-footprint', name: 'Water Usage Footprint Calculator', category: 'miscellaneous' },

  // Finance Niche Calculators
  { id: 'futures-profit', slug: 'futures-profit', name: 'Futures Profit Calculator', category: 'miscellaneous' },
  { id: 'forex-pip', slug: 'forex-pip', name: 'Forex Pip Calculator', category: 'miscellaneous' },
  { id: 'leverage-calculator', slug: 'leverage-calculator', name: 'Leverage Calculator', category: 'miscellaneous' },
  { id: 'margin-requirement', slug: 'margin-requirement', name: 'Margin Requirement Calculator', category: 'miscellaneous' },
  { id: 'sharpe-ratio', slug: 'sharpe-ratio', name: 'Sharpe Ratio Calculator', category: 'miscellaneous' },
  { id: 'sortino-ratio', slug: 'sortino-ratio', name: 'Sortino Ratio Calculator', category: 'miscellaneous' },
  { id: 'kelly-criterion', slug: 'kelly-criterion', name: 'Kelly Criterion Calculator', category: 'miscellaneous' },
  { id: 'value-at-risk', slug: 'value-at-risk', name: 'Value at Risk Calculator', category: 'miscellaneous' },
];

// Export calculator list by category
export function getCalculatorsByCategory(category: string): any[] {
  return allCalculatorDefinitions.filter(calc => calc.category === category);
}

// Export all calculators
export function getAllCalculators(): any[] {
  return allCalculatorDefinitions;
}